### ISSUE TITLE
Are we using the correct rsync endpoint for xml2rfc tools archive?

### ISSUE THREAD

**Issue by strogonoff** [ietf-ribose/bibxml-data-archive-sync#2]
This was the example given by Robert:

```
% rsync rsync.ietf.org::bibxml-ids/reference.I-D.draft-sparks-sipcore-multiple-reasons-00.xml
-rw-r--r--         904 2022/01/14 11:02:47 reference.I-D.draft-sparks-sipcore-multiple-reasons-00.xml

% curl -s https://datatracker.ietf.org/doc/bibxml3/draft-sparks-sipcore-multiple-reasons-00.xml | grep title
      <title>Multiple SIP Reason Header Field Values</title>
```

Looking at GHA here, the URL seems different. I wonder if we are missing some fallback files due to this.

__Originally posted by @rjsparks in https://github.com/ietf-ribose/bibxml-service/issues/110#issuecomment-1036278484__

**Comment by strogonoff** [comment]
or I might have misunderstood how it works and xml2rfc does dynamic resolution/aliasing for draft prefixes.

**Comment by ronaldtse** [comment]
Yes we are. Robert gave us a special endpoint for synching.
